### ISSUE TITLE
Switch from Lombok to AutoValue + Extensions?

### ISSUE THREAD

**Issue by adelnizamutdinov** [fs/android-base#20]
Lombok is too much magic and requires and IDE plugin
AutoValue is JSR 269 and has a number of extensions including Gson/Moshi support and automatic parcelable generation

https://github.com/google/auto/tree/master/value
https://github.com/rharter/auto-value-parcel
https://github.com/rharter/auto-value-moshi

**Comment by IlyaEremin** [comment]
Я не оч в теме, можешь объяснить в двух словах что надо делать чтобы юзать эту штуку и что я получится на выходе?
Если я правильно понимаю, это из той же серии что и 
https://immutables.github.io/typeadapters.html . И она умеет генерить адаптеры для gson -> позволяет избавиться от рефлекшена при де\сериализации и вытекающих из неё проблем.

**Comment by adelnizamutdinov** [comment]
да, из той же серии

AutoValue начинается c генерации equals/hashcode/tostring, для этого я и хотел заменить Lombok на него

но сейчас читаю Immutables и вижу что они умеют все то же, что и AutoValue

кроме Parcelable https://github.com/immutables/immutables/issues/95

вот тут кратко об AutoValue https://speakerdeck.com/jakewharton/autovalue-extensions-square-nyc-march-2016

**Comment by IlyaEremin** [comment]
@adelnizamutdinov а через плагин нагенерить parcelable можно в эти классы?

**Comment by adelnizamutdinov** [comment]
@IlyaEremin я ни разу не пользовался Immutables

**Comment by adelnizamutdinov** [comment]
сейчас вставил autovalue 1.2 в один проект - имею сгенеренные equals/hashcode/tostring

подключил moshi генератор - получил fromJson/toJson без рефлекшена
как понадобится, подключу parcelable генератор

**Comment by IlyaEremin** [comment]
autovalue специфичная вещь, не везде нужна. Пусть base проект будет без какой-либо магии будь то lombok или autovalue.
