### ISSUE TITLE
facebook infer

### ISSUE THREAD

**Issue by adelnizamutdinov** [fs/android-base#24]
I tried running infer on this project, seems to work:

http://grab.by/OUGE

Spotify people use it too:
http://fbinfer.com/blog/2016/03/17/collaboration-with-spotify.html

Someone should try it out on an already evolved Java project and see if it reports anything useful (sadly it doesn't work with Kotlin)

see Travis CI integration here:
https://github.com/facebook/infer/issues/153

**Comment by IlyaEremin** [comment]
If it can give useful information, why not?
